name: Sphinx Documentation Workflow

on:
  push:

jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: 3.12
          activate-environment: sphinx-env

      - name: Install dependencies
        run: |
          conda install pip
          conda activate sphinx-env
          pip install -r ./sphinx_setupkit/requirements.txt

      - name: Generate Sphinx Documentation
        run: |
          cd sphinx_setupkit
          powershell -ExecutionPolicy Bypass -File ./generate_sphinx_docs.ps1
          cd ..

      - name: Build Sphinx documentation
        run: |
          cd docs
          ./make.bat clean
          ./make.bat html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
